# Generated by Django 6.0.8 on 2026-09-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="theatrehall",
            constraint=models.CheckConstraint(
                condition=models.Q(("rows__gte", 1)), name="rows_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="theatrehall",
            constraint=models.CheckConstraint(
                condition=models.Q(("seats_in_row__gte", 1)),
                name="seats_in_row_gte_1",
            ),
        ),
    ]
